name: curso_dart_udemy
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/deivios/curso_dart_udemy

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dio: ^5.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
